
[workspace]
members = [
  "zomes/snapmail",
  "sweettest",
  #"wasm_utils",
  #"proc_macro",
]
resolver = "2"

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

#[patch.crates-io]
#rkv = { git = "https://github.com/holochain/rkv.git", branch = "master" }
#lmdb-rkv = { git = "https://github.com/holochain/lmdb-rs.git" }
