[workspace]
resolver = "2"
members = [
  "crates/delivery_zome_api",
  "zomes/delivery",
  "test_dna/zomes/secret",
  "sweettest",
]

[profile.dev]
lto = false
opt-level = 0
overflow-checks = false

[profile.release.package.snapmail_sweettest]
opt-level = 0
overflow-checks = false

[profile.release]
opt-level = "z"
lto = true # link time optimization

[profile.release.build-override]
opt-level = "z"

[patch.crates-io]
#holochain = { path = "../../../holochain-develop/crates/holochain" }
#holochain_util = { path = "../../../holochain-develop/crates/holochain_util" }
#holochain_conductor_api = { path = "../../../holochain-develop/crates/holochain_conductor_api" }