[workspace]
resolver = "2"
members = [
  "zomes/snapmail",
  "sweettest",
  "wasm_utils",
  "proc_macro",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
#holochain = { path = "../../../holochain-develop/crates/holochain" }
#holochain_util = { path = "../../../holochain-develop/crates/holochain_util" }
#holochain_conductor_api = { path = "../../../holochain-develop/crates/holochain_conductor_api" }