[package]
name = "snapmail_sweettest"
version = "0.0.1"
edition = "2018"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
shrinkwraprs = { version = "0.3.0", default-features = false }
chrono = { version = "=0.4.6", default-features = false }
serde = { version = "1.0", default-features = false }
strum = { version = "0.19", default-features = false }
strum_macros = { version = "0.19", default-features = false }
derive_more = { version = "0.99.9", default-features = false }

futures = { version = "0.3.1", default-features = false }

tokio = { version = "1.3", features = [ "full" ] }
tokio-stream = { version = "0.1", default-features = false }
maplit = { version = "1", default-features = false }

snapmail = { path = "../zomes/snapmail", default-features = false }

# online
holochain = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holochain", default-features = false, features = ["test_utils"] }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holo_hash", default-features = false  }
holochain_zome_types = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holochain_zome_types", default-features = false  }
kitsune_p2p = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "kitsune_p2p", default-features = false  }

# local
#holochain = { path = "../../holochain-develop/crates/holochain", default-features = false, features = ["test_utils"]  }
#holo_hash = { path = "../../holochain-develop/crates/holo_hash", default-features = false  }
#holochain_zome_types = { path = "../../holochain-develop/crates/holochain_zome_types", default-features = false }
#kitsune_p2p = { path = "../../holochain-develop/crates/kitsune_p2p", default-features = false  }
