[package]
name = "snapmail"
version = "0.0.1"
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
#[workspace]

[lib]
name = "snapmail"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
shrinkwraprs = "0.3.0"
chrono = "=0.4.6"
serde = "1.0"
strum = "0.19"
strum_macros = "0.19"
derive_more = "0.99.9"
bincode = "1.1"

snapmail_proc_macro = {path = "../../proc_macro", default-features = false }
# online
hdk = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "hdk", default-features = false }
holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holo_hash", default-features = false }

# local
#hdk = { path = "../../../holochain-develop/crates/hdk", default-features = false }
#holo_hash = { path = "../../../holochain-develop/crates/holo_hash", default-features = false }


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
thiserror = "1.0.24"

# online
holochain_serialized_bytes = "=0.0.50"
#holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization.git" }
holochain = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holochain", default-features = false, features = ["only_check_wasms"] }
holochain_util = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holochain_util", default-features = false }
holochain_conductor_api = { git = "https://github.com/holochain/holochain.git", rev = "cfbcc6a310a4f7dfc35f27c304808d165f602e7a", package = "holochain_conductor_api", default-features = false }

# local
##holochain_serialized_bytes = { git = "https://github.com/holochain/holochain-serialization.git", default-features = false, features = ["only_check_wasms"] }
#holochain = { path = "../../../holochain-develop/crates/holochain", default-features = false }
#holochain_util = { path = "../../../holochain-develop/crates/holochain_util", default-features = false }
#holochain_conductor_api = { path = "../../../holochain-develop/crates/holochain_conductor_api", default-features = false }

