[package]
name = "snapmail"
version = "0.0.1"
edition = "2018"

# Ensure that this is not inside of any other workspace.
# This crate should be an implementation detail of test_utils_wasm and
# therefore shouldn't be mentioned in the top-level Cargo.toml
#[workspace]

[lib]
name = "snapmail"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
shrinkwraprs = "0.3.0"
chrono = "=0.4.6"
serde = "1.0"
strum = "0.19"
strum_macros = "0.19"
derive_more = "0.99.9"

#hdk = { git = "https://github.com/holochain/holochain.git", rev = "1e0fd4fc5052683a97a5279ab92c6720434ebdfd", package = "hdk3" }
#holo_hash = { git = "https://github.com/holochain/holochain.git", rev = "1e0fd4fc5052683a97a5279ab92c6720434ebdfd", package = "holo_hash" }

hdk = { path = "../../../holochain/crates/hdk" }
holo_hash = { path = "../../../holochain/crates/holo_hash" }
#test_wasm_common = { version = "=0.0.1", path = "../../../holochain-rsm/crates/test_utils/wasm_common" }

#dna_help = { path = "../../../../crates/dna_help" }


