/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "delivery" */
export const deliveryFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",
	"commit_private_chunks",
	"commit_private_manifest",
	"complete_manifest",
	"determine_missing_chunks",
	"distribute_parcel",
	"fetch_public_manifest",
	"fetch_chunk",
	"get_delivery_state",
	"get_distribution_state",
	"get_notice",
	"get_notice_state",
	"process_inbox",
	"publish_chunks",
	"publish_chunk",
	"publish_pending_item",
	"publish_public_parcel",
	"pull_public_parcels_details",
	"fetch_parcel_ref",
	"query_DeliveryNotice",
	"query_NoticeAck",
	"query_ReceptionProof",
	"query_all",
	"query_all_Distribution",
	"query_all_DeliveryNotice",
	"query_all_NoticeAck",
	"query_all_NoticeReply",
	"query_all_ReplyAck",
	"query_all_ReceptionProof",
	"query_all_ReceptionAck",
	"query_all_private_manifests",
	"query_all_public_manifests",
	"query_all_public_chunks",
	"query_all_private_chunks",
	"respond_to_notice",
	"scan_incomplete_manifests",
	"scan_orphan_chunks",
	"unpublish_public_parcel",
	"pull_chunk",
];


/** Generate tuple array of function names with given zomeName */
export function generateDeliveryZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of deliveryFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zDelivery" */
export const deliveryZomeFunctions: [ZomeName, FunctionName][] = generateDeliveryZomeFunctionsArray("zDelivery");
