/* This file is generated by zits. Do not edit manually */


/** List of all Link kinds handled by this Zome */
export enum DeliveryLinkType {
	Members = 'Members',
	Inbox = 'Inbox',
	Pendings = 'Pendings',
	PublicParcels = 'PublicParcels',
}
export enum DeliveryUnitEnum {
	DeliveryNotice = 'DeliveryNotice',
	ReceptionAck = 'ReceptionAck',
	NoticeReply = 'NoticeReply',
	Distribution = 'Distribution',
	PrivateChunk = 'PrivateChunk',
	PrivateManifest = 'PrivateManifest',
	ReceptionProof = 'ReceptionProof',
	NoticeAck = 'NoticeAck',
	ReplyAck = 'ReplyAck',
	PendingItem = 'PendingItem',
	PublicManifest = 'PublicManifest',
	PublicChunk = 'PublicChunk',
	PublicParcel = 'PublicParcel',
}
