/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "secret" */
export const secretFunctionNames: FunctionName[] = [
	"entry_defs", 
	"get_zome_info", 
	"get_dna_info",

	"create_secret",
	"create_split_secret",
	"get_secret",
	"get_secrets_from",
	"refuse_secret",
	"accept_secret",
	"send_secret",];


/** Generate tuple array of function names with given zomeName */
export function generateSecretZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   const fns: [ZomeName, FunctionName][] = [];
   for (const fn of secretFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "zSecret" */
export const secretZomeFunctions: [ZomeName, FunctionName][] = generateSecretZomeFunctionsArray("zSecret");
